/**
 * ═══════════════════════════════════════════════════════════
 *  Buckets Core — shared between web (plan-app) and mobile
 * ═══════════════════════════════════════════════════════════
 *
 * Pure TypeScript only — NO React, NO window, NO localStorage.
 * Storage adapters (load/save) live in each app separately:
 *   - plan-app/lib/buckets-store.ts   (localStorage + window events)
 *   - mobile/src/stores/buckets.ts    (AsyncStorage + emitter)
 *
 * When Supabase arrives both adapters will become thin wrappers around
 * the same API. This file — the brain of "צביעת כסף" — stays intact.
 */

/* ═══════════════════════════════════════════════════════════ */
/* Types                                                         */
/* ═══════════════════════════════════════════════════════════ */

/** A single monthly contribution record — populated during check-in */
export interface BucketContribution {
  /** YYYY-MM format, e.g. "2026-04" */
  month: string;
  /** Planned contribution for that month (from bucket.monthlyContribution at the time) */
  planned: number;
  /** What the client actually confirmed they deposited */
  actual: number;
  /** ISO timestamp of when the check-in was confirmed */
  confirmedAt: string;
  /** Optional note from the client */
  note?: string;
}

/** Status of a goal — drives visual styling + recommendations */
export type BucketStatus = "ahead" | "on_track" | "behind" | "at_risk";

/** Priority level — affects sort order & recommendation urgency */
export type BucketPriority = "high" | "medium" | "low";

/** Snapshot of a bucket balance at a point in time */
export interface BucketSnapshot {
  date: string;
  balance: number;
  source: "manual" | "masleka" | "check-in";
}

/** The core Bucket entity */
export interface Bucket {
  /** Stable ID */
  id: string;
  /** Display name, e.g. "דירה לילדים" */
  name: string;
  /** Google Material Symbols icon name */
  icon: string;
  /** Hex color for visual identification — the "color" of the money */
  color: string;

  /* ── Target ───────────────────────── */
  targetAmount: number;
  /** ISO date (YYYY-MM-DD) of target completion */
  targetDate: string;
  priority: BucketPriority;

  /* ── Funding ──────────────────────── */
  currentAmount: number;
  monthlyContribution: number;
  /** Optional: instrument key from the instruments catalog (for tax/return context) */
  fundingSource?: string;

  /* ── Return tracking ──────────────── */
  expectedAnnualReturn: number;
  actualAnnualReturn?: number;

  /* ── Check-in history ─────────────── */
  contributionHistory: BucketContribution[];
  balanceSnapshots: BucketSnapshot[];

  /* ── Initial cash ────────────────── */
  /** One-time lump sum already in hand at goal creation (e.g. ₪70k from selling old car).
   *  Counts toward progress on top of linkedAssets and ongoing contributions. */
  initialCash?: number;

  /* ── Meta ─────────────────────────── */
  createdAt: string;
  updatedAt: string;
  notes?: string;
  archived?: boolean;
  /** Business / personal / mixed tag. Undefined = personal. */
  scope?: "personal" | "business" | "mixed";

  /**
   * Goal category — financial (savings target, retirement, real estate)
   * vs family (life events: bar mitzvah, kid age 18, wedding).
   * Default treated as "financial" when undefined for backwards compat.
   */
  category?: "financial" | "family";

  /**
   * Auto-generated metadata. When the system creates a goal automatically
   * (e.g. bar mitzvah from a kid's DOB), these tags let the UI show the
   * "auto" pill and prevent duplicate generation on each load.
   */
  /**
   * Recurrence pattern. Per Nir 2026-04-27: a car/vacation/celebration is
   * NOT a one-shot — it's a cycle. When set, the goal "renews" on
   * completion: targetDate += periodYears, currentAmount cycles back to
   * 0, cycleNumber increments. Display shows "מחזור N" badge.
   */
  recurrence?: {
    /** Years between cycles (e.g. car every 7, vacation every 1). */
    periodYears: number;
    /** Optional: bump targetAmount each cycle to keep up with inflation. */
    inflationPctPerCycle?: number;
    /** 1-based current cycle number. Increments on auto-rollover. */
    cycleNumber?: number;
  };

  autoGenerated?: {
    /** What seeded this. "system" = default essentials (e.g. emergency fund). */
    source: "kids_savings" | "retirement" | "mortgage" | "manual" | "system";
    /** Reference id in the source store (e.g. kid id). */
    sourceRefId?: string;
    /** Sub-type — useful for kids: "bar_mitzvah" | "age_18" | "age_21" | "emergency_fund" */
    subKind?: string;
    /** True if user has edited this goal — stop auto-overwriting from now on. */
    userEdited?: boolean;
  };

  /**
   * Emergency-fund-specific fields (added 2026-04-28). When `isEmergency`
   * is true, the /goals UI shows a 3/6 month coverage selector instead of
   * the regular target editor; targetAmount is recomputed = monthlyIncome
   * × coverageMonths whenever income changes.
   */
  isEmergency?: boolean;
  coverageMonths?: 3 | 4 | 5 | 6;
}

/* ═══════════════════════════════════════════════════════════ */
/* Constants                                                     */
/* ═══════════════════════════════════════════════════════════ */

/** Curated palette for bucket colors — calm, Finav-style */
export const BUCKET_COLORS = [
  "#0a7a4a", // emerald (default brand)
  "#2563eb", // blue
  "#d97706", // amber
  "#b91c1c", // red
  "#7c3aed", // violet
  "#0891b2", // teal
  "#be185d", // pink
  "#4338ca", // indigo
  "#65a30d", // lime
  "#475569", // slate
] as const;

/** Storage key used by both web (localStorage) and mobile (AsyncStorage) */
export const BUCKETS_STORAGE_KEY = "verdant:buckets";
export const BUCKETS_LEGACY_KEY = "verdant:vision_goals";
export const BUCKETS_EVENT_NAME = "verdant:goals:updated" as const;

/* ═══════════════════════════════════════════════════════════ */
/* ID + Color helpers                                            */
/* ═══════════════════════════════════════════════════════════ */

/** Pick a color deterministically from the palette */
export function pickColor(seed: string | number): string {
  const s = String(seed);
  let hash = 0;
  for (let i = 0; i < s.length; i++) {
    hash = (hash << 5) - hash + s.charCodeAt(i);
    hash |= 0;
  }
  return BUCKET_COLORS[Math.abs(hash) % BUCKET_COLORS.length];
}

/** Generate a stable ID for a new bucket */
export function generateBucketId(): string {
  return `bkt_${Date.now().toString(36)}_${Math.random().toString(36).slice(2, 8)}`;
}

/* ═══════════════════════════════════════════════════════════ */
/* Legacy migration                                              */
/* ═══════════════════════════════════════════════════════════ */

export interface LegacyVisionGoal {
  id: string;
  name: string;
  icon?: string;
  targetAmount: number;
  targetDate: string;
  lumpToday: number;
  monthlyContrib: number;
  annualRate: number;
  priority: BucketPriority;
  instrument?: string;
}

export function migrateLegacyVisionGoals(legacy: LegacyVisionGoal[]): Bucket[] {
  const now = new Date().toISOString();
  return legacy.map((g, i) => ({
    id: g.id || generateBucketId(),
    name: g.name,
    icon: g.icon || "flag",
    color: pickColor(g.id || g.name || i),
    targetAmount: g.targetAmount || 0,
    targetDate: g.targetDate,
    priority: g.priority || "medium",
    currentAmount: g.lumpToday || 0,
    monthlyContribution: g.monthlyContrib || 0,
    fundingSource: g.instrument,
    expectedAnnualReturn: g.annualRate || 0.05,
    actualAnnualReturn: undefined,
    contributionHistory: [],
    balanceSnapshots: g.lumpToday > 0
      ? [{ date: now, balance: g.lumpToday, source: "manual" }]
      : [],
    createdAt: now,
    updatedAt: now,
  }));
}

export interface OnboardingGoalRow {
  name: string;
  cost: string;
  horizon: string;
  priority: string;
}

export function migrateOnboardingGoals(rows: OnboardingGoalRow[]): Bucket[] {
  const now = new Date().toISOString();
  return rows
    .filter(r => r.name && r.cost)
    .map((r, i) => {
      const cost = parseFloat(r.cost.replace(/[^\d.-]/g, "")) || 0;
      const horizonYears = parseFloat(r.horizon) || 5;
      const targetDate = new Date(
        Date.now() + horizonYears * 365.25 * 24 * 3600 * 1000
      ).toISOString().split("T")[0];
      return {
        id: generateBucketId(),
        name: r.name,
        icon: "flag",
        color: pickColor(i),
        targetAmount: cost,
        targetDate,
        priority: (r.priority === "גבוהה" ? "high" :
                   r.priority === "נמוכה" ? "low" : "medium") as BucketPriority,
        currentAmount: 0,
        monthlyContribution: 0,
        expectedAnnualReturn: 0.05,
        contributionHistory: [],
        balanceSnapshots: [],
        createdAt: now,
        updatedAt: now,
      };
    });
}

/* ═══════════════════════════════════════════════════════════ */
/* CRUD Helpers (pure)                                           */
/* ═══════════════════════════════════════════════════════════ */

/** Create a new bucket with sensible defaults */
export function createBucket(
  input: Partial<Bucket> & Pick<Bucket, "name" | "targetAmount" | "targetDate">
): Bucket {
  const now = new Date().toISOString();
  const id = input.id || generateBucketId();
  return {
    id,
    name: input.name,
    icon: input.icon || "flag",
    color: input.color || pickColor(id),
    targetAmount: input.targetAmount,
    targetDate: input.targetDate,
    priority: input.priority || "medium",
    currentAmount: input.currentAmount || 0,
    monthlyContribution: input.monthlyContribution || 0,
    fundingSource: input.fundingSource,
    expectedAnnualReturn: input.expectedAnnualReturn ?? 0.05,
    actualAnnualReturn: input.actualAnnualReturn,
    contributionHistory: input.contributionHistory || [],
    balanceSnapshots: input.balanceSnapshots || (
      input.currentAmount && input.currentAmount > 0
        ? [{ date: now, balance: input.currentAmount, source: "manual" }]
        : []
    ),
    createdAt: input.createdAt || now,
    updatedAt: now,
    notes: input.notes,
    initialCash: input.initialCash || 0,
    isEmergency: input.isEmergency,
    coverageMonths: input.coverageMonths,
  };
}

/** Update a bucket in an array (immutable) */
export function updateBucket(buckets: Bucket[], id: string, patch: Partial<Bucket>): Bucket[] {
  return buckets.map(b =>
    b.id === id
      ? { ...b, ...patch, updatedAt: new Date().toISOString() }
      : b
  );
}

/** Remove a bucket (hard delete) */
export function removeBucket(buckets: Bucket[], id: string): Bucket[] {
  return buckets.filter(b => b.id !== id);
}

/** Record a monthly contribution check-in (immutable) */
export function recordCheckIn(
  bucket: Bucket,
  month: string,
  actual: number,
  note?: string
): Bucket {
  const now = new Date().toISOString();

  const history = bucket.contributionHistory.filter(c => c.month !== month);
  history.push({
    month,
    planned: bucket.monthlyContribution,
    actual,
    confirmedAt: now,
    note,
  });
  history.sort((a, b) => a.month.localeCompare(b.month));

  const newCurrent = bucket.currentAmount + actual;

  const snapshots: BucketSnapshot[] = [
    ...bucket.balanceSnapshots,
    { date: now, balance: newCurrent, source: "check-in" },
  ];

  return {
    ...bucket,
    currentAmount: newCurrent,
    contributionHistory: history,
    balanceSnapshots: snapshots,
    updatedAt: now,
  };
}

/** Record a balance snapshot (immutable) */
export function recordSnapshot(
  bucket: Bucket,
  balance: number,
  source: "manual" | "masleka" = "manual"
): Bucket {
  const now = new Date().toISOString();
  return {
    ...bucket,
    currentAmount: balance,
    balanceSnapshots: [
      ...bucket.balanceSnapshots,
      { date: now, balance, source },
    ],
    updatedAt: now,
  };
}

/* ═══════════════════════════════════════════════════════════ */
/* Aggregates                                                    */
/* ═══════════════════════════════════════════════════════════ */

export function totalBucketBalance(buckets: Bucket[]): number {
  return buckets.reduce((sum, b) => sum + (b.currentAmount || 0), 0);
}

export function totalBucketTarget(buckets: Bucket[]): number {
  return buckets.reduce((sum, b) => sum + (b.targetAmount || 0), 0);
}

export function totalMonthlyContributions(buckets: Bucket[]): number {
  return buckets.reduce((sum, b) => sum + (b.monthlyContribution || 0), 0);
}
