/**
 * Life-events engine — auto-generates family-event Buckets from kids' DOBs.
 *
 * Built 2026-04-29 per Nir's "בנק מטרות" brief. As soon as the user fills
 * in a child's DOB + gender, the system materializes the predictable
 * milestones as goals: bar/bat mitzvah and army release. Idempotent —
 * re-runs safely without duplicating, and preserves user edits.
 *
 * Defaults:
 *   bar_mitzvah:  age 13 (boys),       suggested ₪80,000
 *   bat_mitzvah:  age 12 (girls),      suggested ₪60,000
 *   army_release: age 21 (males) / 20 (females), suggested ₪30,000
 *
 * Each generated bucket is tagged via `autoGenerated.subKind` so we know
 * which event seeded it. If the user manually edits the bucket, we set
 * `autoGenerated.userEdited = true` and stop overwriting from then on.
 */

import { loadBuckets, saveBuckets, createBucket } from "./buckets-store";
import type { Bucket } from "@shared/buckets-core";
import { scopedKey } from "./client-scope";
import { fireSync } from "./sync-engine";
import { BUCKETS_EVENT } from "./buckets-store";

export type Gender = "male" | "female";

interface OnbChildSeed {
  name?: string;
  dob?: string;        // YYYY-MM-DD
  gender?: Gender;
}

interface EventSpec {
  subKind: "bar_mitzvah" | "bat_mitzvah" | "army_release";
  ageYears: number;
  defaultAmount: number;
  icon: string;
  title: (childName: string) => string;
  applies: (gender: Gender | undefined) => boolean;
}

const EVENTS: EventSpec[] = [
  {
    subKind: "bar_mitzvah",
    ageYears: 13,
    defaultAmount: 80_000,
    icon: "celebration",
    title: (n) => `בר מצווה ל${n}`,
    applies: (g) => g !== "female", // default male; missing gender treated as boy
  },
  {
    subKind: "bat_mitzvah",
    ageYears: 12,
    defaultAmount: 60_000,
    icon: "celebration",
    title: (n) => `בת מצווה ל${n}`,
    applies: (g) => g === "female",
  },
  {
    subKind: "army_release",
    ageYears: 21,                // males
    defaultAmount: 30_000,
    icon: "military_tech",
    title: (n) => `שחרור מהצבא ל${n}`,
    applies: (g) => g !== "female",
  },
  {
    subKind: "army_release",
    ageYears: 20,                // females
    defaultAmount: 30_000,
    icon: "military_tech",
    title: (n) => `שחרור מהצבא ל${n}`,
    applies: (g) => g === "female",
  },
];

/** YYYY-MM-DD of `dob + ageYears`. Returns null if dob isn't parseable. */
function targetDateAt(dob: string, ageYears: number): string | null {
  const d = new Date(dob);
  if (isNaN(d.getTime())) return null;
  d.setFullYear(d.getFullYear() + ageYears);
  return d.toISOString().split("T")[0];
}

/**
 * Sync onboarding children → auto life-event buckets.
 * Skips events that already passed (target date in the past).
 * Uses sourceRefId = `${childName}::${subKind}` to detect duplicates.
 */
export function syncChildLifeEvents(children: OnbChildSeed[]): { created: number; skipped: number } {
  if (typeof window === "undefined") return { created: 0, skipped: 0 };
  if (!children?.length) return { created: 0, skipped: 0 };

  const existing = loadBuckets();
  const byRefId = new Map<string, Bucket>();
  for (const b of existing) {
    const ref = b.autoGenerated?.sourceRefId;
    if (ref && b.autoGenerated?.source === "kids_savings") byRefId.set(ref, b);
  }

  let created = 0;
  let skipped = 0;
  const now = new Date();
  const newBuckets: Bucket[] = [];

  for (const child of children) {
    const name = (child.name || "").trim();
    const dob = (child.dob || "").trim();
    if (!name || !dob) continue;

    for (const ev of EVENTS) {
      if (!ev.applies(child.gender)) continue;
      const target = targetDateAt(dob, ev.ageYears);
      if (!target) continue;
      // Skip events already passed
      if (new Date(target).getTime() < now.getTime()) {
        skipped++;
        continue;
      }
      const refId = `${name}::${ev.subKind}`;

      const match = byRefId.get(refId);
      if (match) {
        // Don't overwrite if user edited it; otherwise keep targetDate fresh
        // (it could shift if onboarding DOB was corrected).
        if (match.autoGenerated?.userEdited) { skipped++; continue; }
        if (match.targetDate !== target) {
          match.targetDate = target;
          match.updatedAt = new Date().toISOString();
        }
        continue;
      }

      newBuckets.push(createBucket({
        name: ev.title(name),
        icon: ev.icon,
        targetAmount: ev.defaultAmount,
        targetDate: target,
        priority: ev.subKind === "army_release" ? "low" : "medium",
        category: "family",
        notes: `מטרה אוטומטית — נוצרה משאלון הילדים. עדכן אם הסכום לא מתאים.`,
        autoGenerated: {
          source: "kids_savings",
          sourceRefId: refId,
          subKind: ev.subKind,
        },
      }));
      created++;
    }
  }

  if (created > 0 || newBuckets.length > 0) {
    saveBuckets([...existing, ...newBuckets]);
    fireSync(BUCKETS_EVENT);
  }
  return { created, skipped };
}
