
CREATE TABLE public.israel_cities (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  name text NOT NULL UNIQUE,
  english_name text,
  symbol_code integer
);

ALTER TABLE public.israel_cities ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow public read access on cities"
ON public.israel_cities
FOR SELECT TO authenticated, anon
USING (true);

INSERT INTO public.israel_cities (name, english_name, symbol_code) VALUES
('שם_ישוב', 'שם_ישוב_לועזי', NULL),
('אבו ג''ווייעד )שבט(', 'ABU JUWEI''ID', NULL),
('אבו גוש', 'ABU GHOSH', NULL),
('אבו סנאן', 'ABU SINAN', NULL),
('אבו סריחאן )שבט(', 'ABU SUREIHAN', NULL),
('אבו עבדון )שבט(', 'ABU  ABDUN', NULL),
('אבו עמאר )שבט(', 'ABU  AMMAR', NULL),
('אבו עמרה )שבט(', 'ABU  AMRE', NULL),
('אבו קורינאת )שבט(', 'ABU QUREINAT', NULL),
('אבו קרינאת )יישוב(', 'ABU QUREINAT', NULL),
('אבו רובייעה )שבט(', 'ABU RUBEI''A', NULL),
('אבו רוקייק )שבט(', 'ABU RUQAYYEQ', NULL),
('אבו תלול', 'ABU TULUL', NULL),
('אבטין', 'IBTIN', NULL),
('אבטליון', 'AVTALYON', NULL),
('אביאל', 'AVI''EL', NULL),
('אביבים', 'AVIVIM', NULL),
('אביגדור', 'AVIGEDOR', NULL),
('אביחיל', 'AVIHAYIL', NULL),
('אביטל', 'AVITAL', NULL),
('אביעזר', 'AVI''EZER', NULL),
('אבירים', 'ABBIRIM', NULL),
('אבן יהודה', 'EVEN YEHUDA', NULL),
('אבן מנחם', 'EVEN MENAHEM', NULL),
('אבן ספיר', 'EVEN SAPPIR', NULL),
('אבן שמואל', 'EVEN SHEMU''EL', NULL),
('אבני איתן', 'AVNE ETAN', NULL),
('אבני חפץ', 'AVNE HEFEZ', NULL),
('אבנת', 'AVENAT', NULL),
('אבשלום', 'AVSHALOM', NULL),
('אדורה', 'ADORA', NULL),
('אדירים', 'ADDIRIM', NULL),
('אדמית', 'ADAMIT', NULL),
('אדרת', 'ADDERET', NULL),
('אודים', 'UDIM', NULL),
('אודם', 'ODEM', NULL),
('אוהד', 'OHAD', NULL),
('אום אל-פחם', 'UMM AL-FAHM', NULL),
('אום אל-קוטוף', 'UMM AL-QUTUF', NULL),
('אום בטין', NULL, NULL),
('אומן', 'OMEN', NULL),
('אומץ', 'OMEZ', NULL),
('אופקים', 'OFAQIM', NULL),
('אור הגנוז', 'OR HAGANUZ', NULL),
('אור הנר', 'OR HANER', NULL),
('אור יהודה', 'OR YEHUDA', NULL),
('אור עקיבא', 'OR AQIVA', NULL),
('אורה', 'ORA', NULL),
('אורות', 'OROT', NULL),
('אורטל', 'ORTAL', NULL),
('אורים', 'URIM', NULL),
('אורנים', 'ORANIM', NULL),
('אורנית', 'ORANIT', NULL),
('אושה', 'USHA', NULL),
('אזור', 'AZOR', NULL),
('אחווה', 'AHAWA', NULL),
('אחוזם', 'AHUZZAM', NULL),
('אחוזת ברק', NULL, NULL),
('אחיהוד', 'AHIHUD', NULL),
('אחיטוב', 'AHITUV', NULL),
('אחיסמך', 'AHISAMAKH', NULL),
('אחיעזר', 'AHI''EZER', NULL),
('אטרש )שבט(', 'ATRASH', NULL),
('איבים', 'IBBIM', NULL),
('אייל', 'EYAL', NULL),
('איילת השחר', 'AYYELET HASHAHAR', NULL),
('אילון', 'ELON', NULL),
('אילות', 'ELOT', NULL),
('אילניה', 'ILANIYYA', NULL),
('אילת', 'ELAT', NULL),
('אירוס', 'IRUS', NULL),
('איתמר', 'ITAMAR', NULL),
('איתן', 'ETAN', NULL),
('איתנים', 'ETANIM', NULL),
('אכסאל', 'IKSAL', NULL),
('אל סייד', NULL, NULL),
('אל-עזי', NULL, NULL),
('אל-עריאן', 'AL-ARYAN', NULL),
('אל-רום', 'EL-ROM', NULL),
('אלומה', 'ALUMMA', NULL),
('אלומות', 'ALUMMOT', NULL),
('אלון הגליל', 'ALLON HAGALIL', NULL),
('אלון מורה', 'ELON MORE', NULL),
('אלון שבות', 'ALLON SHEVUT', NULL),
('אלוני אבא', 'ALLONE ABBA', NULL),
('אלוני הבשן', 'ALLONE HABASHAN', NULL),
('אלוני יצחק', 'ALLONE YIZHAQ', NULL),
('אלונים', 'ALLONIM', NULL),
('אלי-עד', 'ELI AL', NULL),
('אליאב', 'ELIAV', NULL),
('אליכין', 'ELYAKHIN', NULL),
('אליפז', 'ELIFAZ', NULL),
('אליפלט', 'ELIFELET', NULL),
('אליקים', 'ELYAQIM', NULL),
('אלישיב', 'ELYASHIV', NULL),
('אלישמע', 'ELISHAMA', NULL),
('אלמגור', 'ALMAGOR', NULL),
('אלמוג', 'ALMOG', NULL),
('אלעד', NULL, NULL),
('אלעזר', 'EL''AZAR', NULL),
('אלפי מנשה', 'ALFE MENASHE', NULL),
('אלקוש', 'ELQOSH', NULL),
('אלקנה', 'ELQANA', NULL),
('אמונים', 'EMUNIM', NULL),
('אמירים', 'AMIRIM', NULL),
('אמנון', 'AMNUN', NULL),
('אמציה', 'AMAZYA', NULL),
('אניעם', 'ANI''AM', NULL),
('אסד )שבט(', 'ASAD', NULL),
('אספר', 'ASEFAR', NULL),
('אעבלין', 'I''BILLIN', NULL),
('אעצם )שבט(', 'A''SAM', NULL),
('אפיניש )שבט(', 'AFEINISH', NULL),
('אפיק', 'AFIQ', NULL),
('אפיקים', 'AFIQIM', NULL),
('אפק', 'AFEQ', NULL),
('אפרת', 'EFRAT', NULL),
('ארבל', 'ARBEL', NULL),
('ארגמן', 'ARGAMAN', NULL),
('ארז', 'EREZ', NULL),
('אריאל', 'ARI''EL', NULL),
('ארסוף', 'ARSUF', NULL),
('אשבול', 'ESHBOL', NULL),
('אשבל', 'NAHAL ESHBAL', NULL),
('אשדוד', 'ASHDOD', NULL),
('אשדות יעקב  )איחוד(', 'ASHDOT YA''AQOV(IHUD)', NULL),
('אשדות יעקב  )מאוחד(', 'ASHDOT YA''AQOV(ME''UH', NULL),
('אשחר', 'ESHHAR', NULL),
('אשכולות', 'ESHKOLOT', NULL),
('אשל הנשיא', 'ESHEL HANASI', NULL),
('אשלים', 'ASHALIM', NULL),
('אשקלון', 'ASHQELON', NULL),
('אשרת', 'ASHERAT', NULL),
('אשתאול', 'ESHTA''OL', NULL),
('אתגר', 'ETGAR', NULL),
('באקה אל-גרביה', NULL, NULL),
('באר אורה', 'BE''ER ORA', NULL),
('באר גנים', 'BEER GANNIM', NULL),
('באר טוביה', 'BE''ER TUVEYA', NULL),
('באר יעקב', 'BE''ER YA''AQOV', NULL),
('באר מילכה', NULL, NULL),
('באר שבע', 'BE''ER SHEVA', NULL),
('בארות יצחק', 'BE''EROT YIZHAQ', NULL),
('בארותיים', 'BE''EROTAYIM', NULL),
('בארי', 'BE''ERI', NULL),
('בוסתן הגליל', 'BUSTAN HAGALIL', NULL),
('בועיינה-נוג''ידאת', 'BU''EINE-NUJEIDAT', NULL),
('בוקעאתא', 'BUQ''ATA', NULL),
('בורגתה', 'BURGETA', NULL),
('בחן', 'BAHAN', NULL),
('בטחה', 'BITHA', NULL),
('ביצרון', 'BIZZARON', NULL),
('ביר אל-מכסור', 'BIR EL-MAKSUR', NULL),
('ביר הדאג''', NULL, NULL),
('ביריה', 'BIRIYYA', NULL),
('בית אורן', 'BET OREN', NULL),
('בית אל', 'BET EL', NULL),
('בית אלעזרי', 'BET EL''AZARI', NULL),
('בית אלפא', 'BET ALFA', NULL),
('בית אריה', 'BET ARYE', NULL),
('בית ברל', 'BET BERL', NULL),
('בית ג''ן', 'BEIT JANN', NULL),
('בית גוברין', 'BET GUVRIN', NULL),
('בית גמליאל', 'BET GAMLI''EL', NULL),
('בית דגן', 'BET DAGAN', NULL),
('בית הגדי', 'BET HAGADDI', NULL),
('בית הלוי', 'BET HALEVI', NULL),
('בית הלל', 'BET HILLEL', NULL),
('בית העמק', 'BET HAEMEQ', NULL),
('בית הערבה', 'BET HAARAVA', NULL),
('בית השיטה', 'BET HASHITTA', NULL),
('בית זיד', 'BET ZEID', NULL),
('בית זית', 'BET ZAYIT', NULL),
('בית זרע', 'BET ZERA', NULL),
('בית חורון', 'BET HORON', NULL),
('בית חירות', 'BET HERUT', NULL),
('בית חלקיה', 'BET HILQIYYA', NULL),
('בית חנן', 'BET HANAN', NULL),
('בית חנניה', 'BET HANANYA', NULL),
('בית חשמונאי', 'BET HASHMONAY', NULL),
('בית יהושע', 'BET YEHOSHUA', NULL),
('בית יוסף', 'BET YOSEF', NULL),
('בית ינאי', 'BET YANNAY', NULL),
('בית יצחק-שער חפר', 'BET YIZHAQ-SH. HEFER', NULL),
('בית לחם הגלילית', 'BET LEHEM HAGELILIT', NULL),
('בית מאיר', 'BET ME''IR', NULL),
('בית נחמיה', 'BET NEHEMYA', NULL),
('בית ניר', 'BET NIR', NULL),
('בית נקופה', 'BET NEQOFA', NULL),
('בית עובד', 'BET OVED', NULL),
('בית עוזיאל', 'BET UZZI''EL', NULL),
('בית עזרא', 'BET EZRA', NULL),
('בית עריף', 'BET ARIF', NULL),
('בית צבי', 'BET ZEVI', NULL),
('בית קמה', 'BET QAMA', NULL),
('בית קשת', 'BET QESHET', NULL),
('בית רבן', 'BET RABBAN', NULL),
('בית רימון', 'BET RIMMON', NULL),
('בית שאן', 'BET SHE''AN', NULL),
('בית שמש', 'BET SHEMESH', NULL),
('בית שערים', 'BET SHE''ARIM', NULL),
('בית שקמה', 'BET SHIQMA', NULL),
('ביתן אהרן', 'BITAN AHARON', NULL),
('ביתר עילית', 'BETAR ILLIT', NULL),
('בלפוריה', 'BALFURIYYA', NULL),
('בן זכאי', 'BEN ZAKKAY', NULL),
('בן עמי', 'BEN AMMI', NULL),
('בן שמן )כפר נוער(', 'BEN SHEMEN(K.NO''AR)', NULL),
('בן שמן )מושב(', 'BEN SHEMEN (MOSHAV)', NULL),
('בני ברק', 'BENE BERAQ', NULL),
('בני דקלים', 'BNE DKALIM', NULL),
('בני דרום', 'BENE DAROM', NULL),
('בני דרור', 'BENE DEROR', NULL),
('בני יהודה', 'BENE YEHUDA', NULL),
('בני נצרים', 'BENE NEZARIM', NULL),
('בני עטרות', 'BENE ATAROT', NULL),
('בני עי"ש', 'BENE AYISH', NULL),
('בני ציון', 'BENE ZIYYON', NULL),
('בני ראם', 'BENE RE''EM', NULL),
('בניה', 'BENAYA', NULL),
('בנימינה-גבעת עדה', 'BINYAMINA', NULL),
('בסמ"ה', 'BASMA', NULL),
('בסמת טבעון', 'BASMAT TAB''UN', NULL),
('בענה', 'BI NE', NULL),
('בצרה', 'BAZRA', NULL),
('בצת', 'BEZET', NULL),
('בקוע', 'BEQOA', NULL),
('בקעות', 'BEQA''OT', NULL),
('בר גיורא', 'BAR GIYYORA', NULL),
('בר יוחאי', 'BAR YOHAY', NULL),
('ברוכין', 'BRUKHIN', NULL),
('ברור חיל', 'BEROR HAYIL', NULL),
('ברוש', 'BEROSH', NULL),
('ברכה', 'BERAKHA', NULL),
('ברכיה', 'BEREKHYA', NULL),
('ברעם', 'BAR''AM', NULL),
('ברק', 'BARAQ', NULL),
('ברקאי', 'BARQAY', NULL),
('ברקן', 'BARQAN', NULL),
('ברקת', 'BAREQET', NULL),
('בת הדר', 'BAT HADAR', NULL),
('בת חן', 'BAT HEN', NULL),
('בת חפר', 'BAT HEFER', NULL),
('בת חצור', 'BAT HAZOR', NULL),
('בת ים', 'BAT YAM', NULL),
('בת עין', 'BAT AYIN', NULL),
('בת שלמה', 'BAT SHELOMO', NULL),
('ג''דיידה-מכר', 'JUDEIDE-MAKER', NULL),
('ג''ולס', 'JULIS', NULL),
('ג''לג''וליה', 'JALJULYE', NULL),
('ג''נאביב )שבט(', 'JUNNABIB', NULL),
('ג''סר א-זרקא', 'JISR AZ-ZARQA', NULL),
('ג''ש )גוש חלב(', 'JISH(GUSH HALAV)', NULL),
('ג''ת', 'JAAT', NULL),
('גאולי תימן', 'GE''ULE TEMAN', NULL),
('גאולים', 'GE''ULIM', NULL),
('גאליה', 'GE''ALYA', NULL),
('גבולות', 'GEVULOT', NULL),
('גבים', 'GEVIM', NULL),
('גבע', 'GEVA', NULL),
('גבע בנימין', 'GEVA BINYAMIN', NULL),
('גבע כרמל', 'GEVA  KARMEL', NULL),
('גבעולים', 'GIV''OLIM', NULL),
('גבעון החדשה', 'GIV''ON HAHADASHA', NULL),
('גבעות בר', NULL, NULL),
('גבעת אבני', 'GIV''AT AVNI', NULL),
('גבעת אלה', 'GIV''AT ELA', NULL),
('גבעת ברנר', 'GIV''AT BRENNER', NULL),
('גבעת השלושה', 'GIV''AT HASHELOSHA', NULL),
('גבעת זאב', 'GIV''AT ZE''EV', NULL),
('גבעת ח"ן', 'GIV''AT HEN', NULL),
('גבעת חיים )איחוד(', 'GIV''AT HAYYIM (IHUD)', NULL),
('גבעת חיים )מאוחד(', 'GIV''AT HAYYIM(ME''UHA', NULL),
('גבעת יואב', 'GIV''AT YO''AV', NULL),
('גבעת יערים', 'GIV''AT YE''ARIM', NULL),
('גבעת ישעיהו', 'GIV''AT YESHA''YAHU', NULL),
('גבעת כ"ח', 'GIV''AT KOAH', NULL),
('גבעת ניל"י', 'GIV''AT NILI', NULL),
('גבעת עוז', 'GIV''AT OZ', NULL),
('גבעת שמואל', 'GIV''AT SHEMU''EL', NULL),
('גבעת שמש', 'GIV''AT SHEMESH', NULL),
('גבעת שפירא', 'GIV''AT SHAPPIRA', NULL),
('גבעתי', 'GIV''ATI', NULL),
('גבעתיים', 'GIV''ATAYIM', NULL),
('גברעם', 'GEVAR''AM', NULL),
('גבת', 'GEVAT', NULL),
('גדות', 'GADOT', NULL),
('גדיש', 'GADISH', NULL),
('גדעונה', 'GID''ONA', NULL),
('גדרה', 'GEDERA', NULL),
('גונן', 'GONEN', NULL),
('גורן', 'GOREN', NULL),
('גורנות הגליל', 'GORNOT HAGALIL', NULL),
('גזית', 'GAZIT', NULL),
('גזר', 'GEZER', NULL),
('גיאה', 'GE''A', NULL),
('גיבתון', 'GIBBETON', NULL),
('גיזו', 'GIZO', NULL),
('גילון', 'GILON', NULL),
('גילת', 'GILAT', NULL),
('גינוסר', 'GINNOSAR', NULL),
('גיניגר', 'GINNEGAR', NULL),
('גינתון', 'GINNATON', NULL),
('גיתה', 'GITTA', NULL),
('גיתית', 'GITTIT', NULL),
('גלאון', 'GAL''ON', NULL),
('גלגל', 'GILGAL', NULL),
('גליל ים', 'GELIL YAM', NULL),
('גלעד )אבן יצחק(', 'EVEN YIZHAQ(GAL''ED)', NULL),
('גמזו', 'GIMZO', NULL),
('גן הדרום', 'GAN HADAROM', NULL),
('גן השומרון', 'GAN HASHOMERON', NULL),
('גן חיים', 'GAN HAYYIM', NULL),
('גן יאשיה', 'GAN YOSHIYYA', NULL),
('גן יבנה', 'GAN YAVNE', NULL),
('גן נר', 'GAN NER', NULL),
('גן שורק', 'GAN SOREQ', NULL),
('גן שלמה', 'GAN SHELOMO', NULL),
('גן שמואל', 'GAN SHEMU''EL', NULL),
('גנות', 'GANNOT', NULL),
('גנות הדר', 'GANNOT HADAR', NULL),
('גני הדר', 'GANNE HADAR', NULL),
('גני טל', NULL, NULL),
('גני יוחנן', 'GANNE YOHANAN', NULL),
('גני מודיעין', 'GANNE MODIIN', NULL),
('גני עם', 'GANNE AM', NULL),
('גני תקווה', 'GANNE TIQWA', NULL),
('געש', 'GA''ASH', NULL),
('געתון', 'GA''TON', NULL),
('גפן', 'GEFEN', NULL),
('גרופית', 'GEROFIT', NULL),
('גשור', 'GESHUR', NULL),
('גשר', 'GESHER', NULL),
('גשר הזיו', 'GESHER HAZIW', NULL),
('גת )קיבוץ(', 'GAT(QIBBUZ)', NULL),
('גת רימון', 'GAT RIMMON', NULL),
('דאלית אל-כרמל', 'DALIYAT AL-KARMEL', NULL),
('דבורה', 'DEVORA', NULL),
('דבוריה', 'DABBURYE', NULL),
('דבירה', 'DEVIRA', NULL),
('דברת', 'DAVERAT', NULL),
('דגניה א''', 'DEGANYA ALEF', NULL),
('דגניה ב''', 'DEGANYA BET', NULL),
('דוב"ב', 'DOVEV', NULL),
('דולב', 'DOLEV', NULL),
('דור', 'DOR', NULL),
('דורות', 'DOROT', NULL),
('דחי', 'DAHI', NULL),
('דייר אל-אסד', 'DEIR AL-ASAD', NULL),
('דייר חנא', 'DEIR HANNA', NULL),
('דייר ראפאת', 'DEIR RAFAT', NULL),
('דימונה', 'DIMONA', NULL),
('דישון', 'DISHON', NULL),
('דליה', 'DALIYYA', NULL),
('דלתון', 'DALTON', NULL),
('דמיידה', 'DEMEIDE', NULL),
('דן', 'DAN', NULL),
('דפנה', 'DAFNA', NULL),
('דקל', 'DEQEL', NULL),
('דריג''את', NULL, NULL),
('האון', 'HAON', NULL),
('הבונים', 'HABONIM', NULL),
('הגושרים', 'HAGOSHERIM', NULL),
('הדר עם', 'HADAR AM', NULL),
('הוד השרון', 'HOD HASHARON', NULL),
('הודיה', 'HODIYYA', NULL),
('הודיות', 'HODAYOT', NULL),
('הוואשלה )שבט(', 'HAWASHLA', NULL),
('הוזייל )שבט(', 'HUZAYYEL', NULL),
('הושעיה', 'HOSHA''AYA', NULL),
('הזורע', 'HAZOREA', NULL),
('הזורעים', 'HAZORE''IM', NULL),
('החותרים', 'HAHOTERIM', NULL),
('היוגב', 'HAYOGEV', NULL),
('הילה', 'HILLA', NULL),
('המעפיל', 'HAMA''PIL', NULL),
('הסוללים', 'HASOLELIM', NULL),
('העוגן', 'HAOGEN', NULL),
('הר אדר', 'HAR ADAR', NULL),
('הר גילה', 'HAR GILLO', NULL),
('הר עמשא', 'HAR AMASA', NULL),
('הראל', 'HAR''EL', NULL),
('הרדוף', 'HARDUF', NULL),
('הרצליה', 'HERZELIYYA', NULL),
('הררית', 'HARARIT', NULL),
('ורד יריחו', 'WERED YERIHO', NULL),
('ורדון', 'WARDON', NULL),
('זבארגה )שבט(', 'ZABARGA', NULL),
('זבדיאל', 'ZAVDI''EL', NULL),
('זוהר', 'ZOHAR', NULL),
('זיקים', 'ZIQIM', NULL),
('זיתן', 'ZETAN', NULL),
('זכרון יעקב', 'ZIKHRON YA''AQOV', NULL),
('זכריה', 'ZEKHARYA', NULL),
('זמר', 'ZEMER', NULL),
('זמרת', 'ZIMRAT', NULL),
('זנוח', 'ZANOAH', NULL),
('זרועה', 'ZERU''A', NULL),
('זרזיר', 'ZARZIR', NULL),
('זרחיה', 'ZERAHYA', NULL),
('ח''ואלד', NULL, NULL),
('ח''ואלד )שבט(', 'KHAWALED', NULL),
('חבצלת השרון', 'HAVAZZELET HASHARON', NULL),
('חבר', 'HEVER', NULL),
('חברון', NULL, NULL),
('חגור', 'HAGOR', NULL),
('חגי', 'HAGGAI', NULL),
('חגלה', 'HOGLA', NULL),
('חד-נס', 'HAD-NES', NULL),
('חדיד', 'HADID', NULL),
('חדרה', 'HADERA', NULL),
('חוג''ייראת )ד''הרה(', 'HUJEIRAT (DAHRA)', NULL),
('חולדה', 'HULDA', NULL),
('חולון', 'HOLON', NULL),
('חולית', 'HOLIT', NULL),
('חולתה', 'HULATA', NULL),
('חוסן', 'HOSEN', NULL),
('חוסנייה', 'HUSSNIYYA', NULL),
('חופית', 'HOFIT', NULL),
('חוקוק', 'HUQOQ', NULL),
('חורה', 'HURA', NULL),
('חורפיש', 'HURFEISH', NULL),
('חורשים', 'HORESHIM', NULL),
('חזון', 'HAZON', NULL),
('חיבת ציון', 'HIBBAT ZIYYON', NULL),
('חיננית', 'HINNANIT', NULL),
('חיפה', 'HAIFA', NULL),
('חירות', 'HERUT', NULL),
('חלוץ', 'HALUZ', NULL),
('חלמיש', 'HALLAMISH', NULL),
('חלץ', 'HELEZ', NULL),
('חמאם', 'HAMAM', NULL),
('חמד', 'HEMED', NULL),
('חמדיה', 'HAMADYA', NULL),
('חמדת', 'NAHAL HEMDAT', NULL),
('חמרה', 'HAMRA', NULL),
('חניאל', 'HANNI''EL', NULL),
('חניתה', 'HANITA', NULL),
('חנתון', 'HANNATON', NULL),
('חספין', 'HASPIN', NULL),
('חפץ חיים', 'HAFEZ HAYYIM', NULL),
('חפצי-בה', 'HEFZI-BAH', NULL),
('חצב', 'HAZAV', NULL),
('חצבה', 'HAZEVA', NULL),
('חצור הגלילית', 'HAZOR HAGELILIT', NULL),
('חצור-אשדוד', 'HAZOR-ASHDOD', NULL),
('חצר בארותיים', 'HAZAR BE''EROTAYIM', NULL),
('חצרות חולדה', 'HAZROT HULDA', NULL),
('חצרות יסף', 'HAZROT YASAF', NULL),
('חצרות כ"ח', 'HAZROT KOAH', NULL),
('חצרים', 'HAZERIM', NULL),
('חרב לאת', 'HEREV LE''ET', NULL),
('חרוצים', 'HARUZIM', NULL),
('חריש', 'HARISH', NULL),
('חרמש', 'HERMESH', NULL),
('חרשים', 'HARASHIM', NULL),
('חשמונאים', 'HASHMONA''IM', NULL),
('טבריה', 'TIBERIAS', NULL),
('טובא-זנגריה', 'TUBA-ZANGARIYYE', NULL),
('טורעאן', 'TUR''AN', NULL),
('טייבה', 'TAYIBE', NULL),
('טייבה )בעמק(', 'TAYIBE(BAEMEQ)', NULL),
('טירה', 'TIRE', NULL),
('טירת יהודה', 'TIRAT YEHUDA', NULL),
('טירת כרמל', 'TIRAT KARMEL', NULL),
('טירת צבי', 'TIRAT ZEVI', NULL),
('טל שחר', 'TAL SHAHAR', NULL),
('טל-אל', 'TAL-EL', NULL),
('טללים', 'TELALIM', NULL),
('טלמון', 'TALMON', NULL),
('טמרה', 'TAMRA', NULL),
('טמרה )יזרעאל(', 'TAMRA (YIZRE''EL)', NULL),
('טנא', 'TENE', NULL),
('טפחות', 'TEFAHOT', NULL),
('יאנוח-ג''ת', 'YANUH-JAT', NULL),
('יבול', 'YEVUL', NULL),
('יבנאל', 'YAVNE''EL', NULL),
('יבנה', 'YAVNE', NULL),
('יגור', 'YAGUR', NULL),
('יגל', 'YAGEL', NULL),
('יד בנימין', 'YAD BINYAMIN', NULL),
('יד השמונה', 'YAD HASHEMONA', NULL),
('יד חנה', 'YAD HANNA', NULL),
('יד מרדכי', 'YAD MORDEKHAY', NULL),
('יד נתן', 'YAD NATAN', NULL),
('יד רמב"ם', 'YAD RAMBAM', NULL),
('ידידה', 'YEDIDA', NULL),
('יהוד-מונוסון', 'YEHUD-MONOSON', NULL),
('יהל', 'YAHEL', NULL),
('יובל', 'YUVAL', NULL),
('יובלים', 'YUVALIM', NULL),
('יודפת', 'YODEFAT', NULL),
('יונתן', 'YONATAN', NULL),
('יושיביה', 'YOSHIVYA', NULL),
('יזרעאל', 'YIZRE''EL', NULL),
('יחיעם', 'YEHI''AM', NULL),
('יטבתה', 'YOTVATA', NULL),
('ייט"ב', 'YITAV', NULL),
('יכיני', 'YAKHINI', NULL),
('ינוב', 'YANUV', NULL),
('ינון', 'YINNON', NULL),
('יסוד המעלה', 'YESUD HAMA''ALA', NULL),
('יסודות', 'YESODOT', NULL),
('יסעור', 'YAS''UR', NULL),
('יעד', 'YA''AD', NULL),
('יעל', 'YA''EL', NULL),
('יעף', 'YE''AF', NULL),
('יערה', 'YA''ARA', NULL),
('יפיע', 'YAFI', NULL),
('יפית', 'YAFIT', NULL),
('יפעת', 'YIF''AT', NULL),
('יפתח', 'YIFTAH', NULL),
('יצהר', 'YIZHAR', NULL),
('יציץ', 'YAZIZ', NULL),
('יקום', 'YAQUM', NULL),
('יקיר', 'YAQIR', NULL),
('יקנעם )מושבה(', 'YOQNE''AM(MOSHAVA)', NULL),
('יקנעם עילית', 'YOQNE''AM ILLIT', NULL),
('יראון', 'YIR''ON', NULL),
('ירדנה', 'YARDENA', NULL),
('ירוחם', 'YEROHAM', NULL),
('ירושלים', 'JERUSALEM', NULL),
('ירחיב', 'YARHIV', NULL),
('ירכא', 'YIRKA', NULL),
('ירקונה', 'YARQONA', NULL),
('ישע', 'YESHA', NULL),
('ישעי', 'YISH''I', NULL),
('ישרש', 'YASHRESH', NULL),
('יתד', 'YATED', NULL),
('יתיר', NULL, NULL),
('כאבול', 'KABUL', NULL),
('כאוכב אבו אל-היג''א', 'KAOKAB ABU AL-HIJA', NULL),
('כברי', 'KABRI', NULL),
('כדורי', 'KADOORIE', NULL),
('כדיתה', NULL, NULL),
('כוכב השחר', 'KOKHAV HASHAHAR', NULL),
('כוכב יאיר', 'KOKHAV YA''IR', NULL),
('כוכב יעקב', 'KOKHAV YA''AQOV', NULL),
('כוכב מיכאל', 'KOKHAV MIKHA''EL', NULL),
('כורזים', 'KORAZIM', NULL),
('כחל', 'KAHAL', NULL),
('כחלה', NULL, NULL),
('כיסופים', 'KISSUFIM', NULL),
('כישור', 'KISHOR', NULL),
('כליל', 'KELIL', NULL),
('כלנית', 'KALLANIT', NULL),
('כמאנה', NULL, NULL),
('כמהין', 'KEMEHIN', NULL),
('כמון', 'KAMMON', NULL),
('כנות', 'KANNOT', NULL),
('כנף', 'KANAF', NULL),
('כנרת )מושבה(', 'KINNERET(MOSHAVA)', NULL),
('כנרת )קבוצה(', 'KINNERET(QEVUZA)', NULL),
('כסיפה', 'KUSEIFE', NULL),
('כסלון', 'KESALON', NULL),
('כסרא-סמיע', 'KISRA-SUMEI', NULL),
('כעביה-טבאש-חג''אג''רה', 'KA''ABIYYE-TABBASH-HA', NULL),
('כפר אביב', 'KEFAR AVIV', NULL),
('כפר אדומים', 'KEFAR ADUMMIM', NULL),
('כפר אוריה', 'KEFAR URIYYA', NULL),
('כפר אחים', 'KEFAR AHIM', NULL),
('כפר ביאליק', 'KEFAR BIALIK', NULL),
('כפר ביל"ו', 'KEFAR BILU', NULL),
('כפר בלום', 'KEFAR BLUM', NULL),
('כפר בן נון', 'KEFAR BIN NUN', NULL),
('כפר ברא', 'KAFAR BARA', NULL),
('כפר ברוך', 'KEFAR BARUKH', NULL),
('כפר גדעון', 'KEFAR GID''ON', NULL),
('כפר גלים', 'KEFAR GALLIM', NULL),
('כפר גליקסון', 'KEFAR GLIKSON', NULL),
('כפר גלעדי', 'KEFAR GIL''ADI', NULL),
('כפר דניאל', 'KEFAR DANIYYEL', NULL),
('כפר האורנים', 'KEFAR HAORANIM', NULL),
('כפר החורש', 'KEFAR HAHORESH', NULL),
('כפר המכבי', 'KEFAR HAMAKKABI', NULL),
('כפר הנגיד', 'KEFAR HANAGID', NULL),
('כפר הנוער הדתי', 'KEFAR HANO''AR HADATI', NULL),
('כפר הנשיא', 'KEFAR HANASI', NULL),
('כפר הס', 'KEFAR HESS', NULL),
('כפר הרא"ה', 'KEFAR HARO''E', NULL),
('כפר הרי"ף', 'KEFAR HARIF', NULL),
('כפר ויתקין', 'KEFAR VITKIN', NULL),
('כפר ורבורג', 'KEFAR WARBURG', NULL),
('כפר ורדים', 'KEFAR WERADIM', NULL),
('כפר זוהרים', 'KEFAR ZOHARIM', NULL),
('כפר זיתים', 'KEFAR ZETIM', NULL),
('כפר חב"ד', 'KEFAR HABAD', NULL),
('כפר חושן', 'KEFAR HOSHEN', NULL),
('כפר חיטים', 'KEFAR HITTIM', NULL),
('כפר חיים', 'KEFAR HAYYIM', NULL),
('כפר חנניה', 'KEFAR HANANYA', NULL),
('כפר חסידים א''', 'KEFAR HASIDIM ALEF', NULL),
('כפר חסידים ב''', 'KEFAR HASIDIM BET', NULL),
('כפר חרוב', 'KEFAR HARUV', NULL),
('כפר טרומן', 'KEFAR TRUMAN', NULL),
('כפר יאסיף', 'KAFAR YASIF', NULL),
('כפר ידידיה', 'YEDIDYA', NULL),
('כפר יהושע', 'KEFAR YEHOSHUA', NULL),
('כפר יונה', 'KEFAR YONA', NULL),
('כפר יחזקאל', 'KEFAR YEHEZQEL', NULL),
('כפר יעבץ', 'KEFAR YA''BEZ', NULL),
('כפר כמא', 'KAFAR KAMA', NULL),
('כפר כנא', 'KAFAR KANNA', NULL),
('כפר מונש', 'KEFAR MONASH', NULL),
('כפר מימון', 'KEFAR MAYMON', NULL),
('כפר מל"ל', 'KEFAR MALAL', NULL),
('כפר מנדא', 'KAFAR MANDA', NULL),
('כפר מנחם', 'KEFAR MENAHEM', NULL),
('כפר מסריק', 'KEFAR MASARYK', NULL),
('כפר מצר', 'KAFAR MISR', NULL),
('כפר מרדכי', 'KEFAR MORDEKHAY', NULL),
('כפר נטר', 'KEFAR NETTER', NULL),
('כפר סאלד', 'KEFAR SZOLD', NULL),
('כפר סבא', 'KEFAR SAVA', NULL),
('כפר סילבר', 'KEFAR SILVER', NULL),
('כפר סירקין', 'KEFAR SIRKIN', NULL),
('כפר עבודה', 'KEFAR AVODA', NULL),
('כפר עזה', 'KEFAR AZZA', NULL),
('כפר עציון', 'KEFAR EZYON', NULL),
('כפר פינס', 'KEFAR PINES', NULL),
('כפר קאסם', 'KAFAR QASEM', NULL),
('כפר קיש', 'KEFAR KISH', NULL),
('כפר קרע', 'KAFAR QARA', NULL),
('כפר ראש הנקרה', 'KEFAR ROSH HANIQRA', NULL),
('כפר רוזנואלד )זרעית(', 'KEFAR ROZENWALD(ZAR.', NULL),
('כפר רופין', 'KEFAR RUPPIN', NULL),
('כפר רות', 'KEFAR RUT', NULL),
('כפר שמאי', 'KEFAR SHAMMAY', NULL),
('כפר שמואל', 'KEFAR SHEMU''EL', NULL),
('כפר שמריהו', 'KEFAR SHEMARYAHU', NULL),
('כפר תבור', 'KEFAR TAVOR', NULL),
('כפר תפוח', 'KEFAR TAPPUAH', NULL),
('כרי דשא', 'KARE DESHE', NULL),
('כרכום', 'KARKOM', NULL),
('כרם בן זמרה', 'KEREM BEN ZIMRA', NULL),
('כרם בן שמן', 'KEREM BEN SHEMEN', NULL),
('כרם יבנה )ישיבה(', 'KEREM YAVNE(YESHIVA)', NULL),
('כרם מהר"ל', 'KEREM MAHARAL', NULL),
('כרם שלום', 'KEREM SHALOM', NULL),
('כרמי יוסף', 'KARME YOSEF', NULL),
('כרמי צור', 'KARME ZUR', NULL),
('כרמי קטיף', 'KARME QATIF', NULL),
('כרמיאל', 'KARMI''EL', NULL),
('כרמיה', 'KARMIYYA', NULL),
('כרמים', 'KERAMIM', NULL),
('כרמל', 'KARMEL', NULL),
('לא רשום', NULL, NULL),
('לבון', 'LAVON', NULL),
('לביא', 'LAVI', NULL),
('לבנים', 'LIVNIM', NULL),
('להב', 'LAHAV', NULL),
('להבות הבשן', 'LAHAVOT HABASHAN', NULL),
('להבות חביבה', 'LAHAVOT HAVIVA', NULL),
('להבים', 'LEHAVIM', NULL),
('לוד', 'LOD', NULL),
('לוזית', 'LUZIT', NULL),
('לוחמי הגיטאות', 'LOHAME HAGETA''OT', NULL),
('לוטם', 'LOTEM', NULL),
('לוטן', 'LOTAN', NULL),
('לימן', 'LIMAN', NULL),
('לכיש', 'LAKHISH', NULL),
('לפיד', 'LAPPID', NULL),
('לפידות', 'LAPPIDOT', NULL),
('לקיה', 'LAQYE', NULL),
('מאור', 'MA''OR', NULL),
('מאיר שפיה', 'ME''IR SHEFEYA', NULL),
('מבוא ביתר', 'MEVO BETAR', NULL),
('מבוא דותן', 'MEVO DOTAN', NULL),
('מבוא חורון', 'MEVO HORON', NULL),
('מבוא חמה', 'MEVO HAMMA', NULL),
('מבוא מודיעים', 'MEVO MODI''IM', NULL),
('מבואות ים', 'MEVO''OT YAM', NULL),
('מבועים', 'MABBU''IM', NULL),
('מבטחים', 'MIVTAHIM', NULL),
('מבקיעים', 'MAVQI''IM', NULL),
('מבשרת ציון', 'MEVASSERET ZIYYON', NULL),
('מג''ד אל-כרום', 'MAJD AL-KURUM', NULL),
('מג''דל שמס', 'MAJDAL SHAMS', NULL),
('מגאר', 'MUGHAR', NULL),
('מגדים', 'MEGADIM', NULL),
('מגדל', 'MIGDAL', NULL),
('מגדל העמק', 'MIGDAL HAEMEQ', NULL),
('מגדל עוז', 'MIGDAL OZ', NULL),
('מגדלים', 'MIGDALIM', NULL),
('מגידו', 'MEGIDDO', NULL),
('מגל', 'MAGGAL', NULL),
('מגן', 'MAGEN', NULL),
('מגן שאול', 'MAGEN SHA''UL', NULL),
('מגשימים', 'MAGSHIMIM', NULL),
('מדרך עוז', 'MIDRAKH OZ', NULL),
('מדרשת בן גוריון', 'MIDRESHET BEN GURION', NULL),
('מדרשת רופין', 'MIDRESHET RUPPIN', NULL),
('מודיעין עילית', 'MODI''IN ILLIT', NULL),
('מודיעין-מכבים-רעות', 'MODI''IN-MAKKABBIM-RE', NULL),
('מולדה', NULL, NULL),
('מולדת', 'MOLEDET', NULL),
('מוצא עילית', 'MOZA ILLIT', NULL),
('מוקייבלה', 'MUQEIBLE', NULL),
('מורן', 'MORAN', NULL),
('מורשת', 'MORESHET', NULL),
('מזור', 'MAZOR', NULL),
('מזכרת בתיה', 'MAZKERET BATYA', NULL),
('מזרע', 'MIZRA', NULL),
('מזרעה', 'MAZRA''A', NULL),
('מחולה', 'MEHOLA', NULL),
('מחנה הילה', NULL, NULL),
('מחנה טלי', NULL, NULL),
('מחנה יהודית', NULL, NULL),
('מחנה יוכבד', NULL, NULL),
('מחנה יפה', NULL, NULL),
('מחנה יתיר', 'MAHANE YATTIR', NULL),
('מחנה מרים', NULL, NULL),
('מחנה עדי', NULL, NULL),
('מחנה תל נוף', NULL, NULL),
('מחניים', 'MAHANAYIM', NULL),
('מחסיה', 'MAHSEYA', NULL),
('מטולה', 'METULA', NULL),
('מטע', 'MATTA', NULL),
('מי עמי', 'ME AMMI', NULL),
('מיטב', 'METAV', NULL),
('מייסר', 'MEISER', NULL),
('מיצר', 'MEZAR', NULL),
('מירב', 'MERAV', NULL),
('מירון', 'MERON', NULL),
('מישר', 'MESHAR', NULL),
('מיתר', 'METAR', NULL),
('מכורה', 'MEKHORA', NULL),
('מכחול', 'MAKCHUL', NULL),
('מכמורת', 'MIKHMORET', NULL),
('מכמנים', 'MIKHMANNIM', NULL),
('מלאה', 'MELE''A', NULL),
('מלילות', 'MELILOT', NULL),
('מלכיה', 'MALKIYYA', NULL),
('מלכישוע', 'MALKISHUA', NULL),
('מנוחה', 'MENUHA', NULL),
('מנוף', 'MANOF', NULL),
('מנות', 'MANOT', NULL),
('מנחמיה', 'MENAHEMYA', NULL),
('מנרה', 'MENNARA', NULL),
('מנשית זבדה', 'MANSHIYYET ZABDA', NULL),
('מסד', 'MASSAD', NULL),
('מסדה', 'MASSADA', NULL),
('מסילות', 'MESILLOT', NULL),
('מסילת ציון', 'MESILLAT ZIYYON', NULL),
('מסלול', 'MASLUL', NULL),
('מסעדה', 'MAS''ADE', NULL),
('מסעודין אל-עזאזמה', 'MAS''UDIN AL-''AZAZME', NULL),
('מעברות', 'MA''BAROT', NULL),
('מעגלים', 'MA''GALIM', NULL),
('מעגן', 'MA''AGAN', NULL),
('מעגן מיכאל', 'MA''AGAN MIKHA''EL', NULL),
('מעוז חיים', 'MA''OZ HAYYIM', NULL),
('מעון', 'MA''ON', NULL),
('מעונה', 'ME''ONA', NULL),
('מעיליא', 'MI''ELYA', NULL),
('מעין ברוך', 'MA''YAN BARUKH', NULL),
('מעין צבי', 'MA''YAN ZEVI', NULL),
('מעלה אדומים', 'MA''ALE ADUMMIM', NULL),
('מעלה אפרים', 'MA''ALE EFRAYIM', NULL),
('מעלה גלבוע', 'MA''ALE GILBOA', NULL),
('מעלה גמלא', 'MA''ALE GAMLA', NULL),
('מעלה החמישה', 'MA''ALE HAHAMISHA', NULL),
('מעלה לבונה', 'MA''ALE LEVONA', NULL),
('מעלה מכמש', 'MA''ALE MIKHMAS', NULL),
('מעלה עירון', 'MA''ALE IRON', NULL),
('מעלה עמוס', 'MA''ALE AMOS', NULL),
('מעלה שומרון', 'MA''ALE SHOMERON', NULL),
('מעלות-תרשיחא', 'MA''ALOT-TARSHIHA', NULL),
('מענית', 'MA''ANIT', NULL),
('מעש', 'MA''AS', NULL),
('מפלסים', 'MEFALLESIM', NULL),
('מצדות יהודה', 'MEZADOT YEHUDA', NULL),
('מצובה', 'MAZZUVA', NULL),
('מצליח', 'MAZLIAH', NULL),
('מצפה', 'MIZPA', NULL),
('מצפה אבי"ב', 'MIZPE AVIV', NULL),
('מצפה אילן', NULL, NULL),
('מצפה יריחו', 'MIZPE YERIHO', NULL),
('מצפה נטופה', 'MIZPE NETOFA', NULL),
('מצפה רמון', 'MIZPE RAMON', NULL),
('מצפה שלם', 'MIZPE SHALEM', NULL),
('מצר', 'MEZER', NULL),
('מקווה ישראל', 'MIQWE YISRA''EL', NULL),
('מרגליות', 'MARGALIYYOT', NULL),
('מרום גולן', 'MEROM GOLAN', NULL),
('מרחב עם', NULL, NULL),
('מרחביה )מושב(', 'MERHAVYA(MOSHAV)', NULL),
('מרחביה )קיבוץ(', 'MERHAVYA(QIBBUZ)', NULL),
('מרכז שפירא', 'MERKAZ SHAPPIRA', NULL),
('משאבי שדה', 'MASH''ABBE SADE', NULL),
('משגב דב', 'MISGAV DOV', NULL),
('משגב עם', 'MISGAV AM', NULL),
('משהד', 'MESHHED', NULL),
('משואה', 'MASSU''A', NULL),
('משואות יצחק', 'MASSUOT YIZHAQ', NULL),
('משכיות', 'MASKIYYOT', NULL),
('משמר איילון', 'MISHMAR AYYALON', NULL),
('משמר דוד', 'MISHMAR DAWID', NULL),
('משמר הירדן', 'MISHMAR HAYARDEN', NULL),
('משמר הנגב', 'MISHMAR HANEGEV', NULL),
('משמר העמק', 'MISHMAR HAEMEQ', NULL),
('משמר השבעה', 'MISHMAR HASHIV''A', NULL),
('משמר השרון', 'MISHMAR HASHARON', NULL),
('משמרות', 'MISHMAROT', NULL),
('משמרת', 'MISHMERET', NULL),
('משען', 'MASH''EN', NULL),
('מתן', 'MATTAN', NULL),
('מתת', 'MATTAT', NULL),
('מתתיהו', 'MATTITYAHU', NULL),
('נאות גולן', 'NE''OT GOLAN', NULL),
('נאות הכיכר', 'NE''OT HAKIKKAR', NULL),
('נאות מרדכי', 'NE''OT MORDEKHAY', NULL),
('נאות סמדר', 'SHIZZAFON', NULL),
('נאעורה', 'NA''URA', NULL),
('נבטים', 'NEVATIM', NULL),
('נגבה', 'NEGBA', NULL),
('נגוהות', NULL, NULL),
('נהורה', 'NEHORA', NULL),
('נהלל', 'NAHALAL', NULL),
('נהריה', 'NAHARIYYA', NULL),
('נוב', 'NOV', NULL),
('נוגה', 'NOGAH', NULL),
('נווה', 'NAVE', NULL),
('נווה אבות', 'NEWE AVOT', NULL),
('נווה אור', 'NEWE UR', NULL),
('נווה אטי"ב', 'NEWE ATIV', NULL),
('נווה אילן', 'NEWE ILAN', NULL),
('נווה איתן', 'NEWE ETAN', NULL),
('נווה דניאל', 'NEWE DANIYYEL', NULL),
('נווה זוהר', 'NEWE ZOHAR', NULL),
('נווה זיו', NULL, NULL),
('נווה חריף', 'NEWE HARIF', NULL),
('נווה ים', 'NEWE YAM', NULL),
('נווה ימין', 'NEWE YAMIN', NULL),
('נווה ירק', 'NEWE YARAQ', NULL),
('נווה מבטח', 'NEWE MIVTAH', NULL),
('נווה מיכאל', 'NEWE MIKHA''EL', NULL),
('נווה שלום', 'NEWE SHALOM', NULL),
('נועם', 'NO''AM', NULL),
('נוף איילון', NULL, NULL),
('נופים', 'NOFIM', NULL),
('נופית', 'NOFIT', NULL),
('נופך', 'NOFEKH', NULL),
('נוקדים', 'NOQEDIM', NULL),
('נורדיה', 'NORDIYYA', NULL),
('נורית', 'NURIT', NULL),
('נחושה', 'NEHUSHA', NULL),
('נחל עוז', 'NAHAL OZ', NULL),
('נחלה', 'NAHALA', NULL),
('נחליאל', 'NAHALI''EL', NULL),
('נחלים', 'NEHALIM', NULL),
('נחם', 'NAHAM', NULL),
('נחף', 'NAHEF', NULL),
('נחשולים', 'NAHSHOLIM', NULL),
('נחשון', 'NAHSHON', NULL),
('נחשונים', 'NAHSHONIM', NULL),
('נטועה', 'NETU''A', NULL),
('נטור', 'NATUR', NULL),
('נטע', 'NETA', NULL),
('נטעים', 'NETA''IM', NULL),
('נטף', 'NATAF', NULL),
('ניין', 'NEIN', NULL),
('ניל"י', 'NILI', NULL),
('ניצן', 'NIZZAN', NULL),
('ניצן ב''', 'NIZZAN B', NULL),
('ניצנה )קהילת חינוך(', 'NIZZANA (QEHILAT HIN', NULL),
('ניצני סיני', 'NIZZANE SINAY', NULL),
('ניצני עוז', 'NIZZANE OZ', NULL),
('ניצנים', 'NIZZANIM', NULL),
('ניר אליהו', 'NIR ELIYYAHU', NULL),
('ניר בנים', 'NIR BANIM', NULL),
('ניר גלים', 'NIR GALLIM', NULL),
('ניר דוד )תל עמל(', 'NIR DAWID (TEL AMAL)', NULL),
('ניר ח"ן', 'NIR HEN', NULL),
('ניר יפה', 'NIR YAFE', NULL),
('ניר יצחק', 'NIR YIZHAQ', NULL),
('ניר ישראל', 'NIR YISRA''EL', NULL),
('ניר משה', 'NIR MOSHE', NULL),
('ניר עוז', 'NIR OZ', NULL),
('ניר עם', 'NIR AM', NULL),
('ניר עציון', 'NIR EZYON', NULL),
('ניר עקיבא', 'NIR AQIVA', NULL),
('ניר צבי', 'NIR ZEVI', NULL),
('נירים', 'NIRIM', NULL),
('נירית', 'NIRIT', NULL),
('נירן', 'NIRAN', NULL),
('נמרוד', 'NIMROD', NULL),
('נס הרים', 'NES HARIM', NULL),
('נס עמים', 'NES AMMIM', NULL),
('נס ציונה', 'NES ZIYYONA', NULL),
('נעורים', 'NE''URIM', NULL),
('נעלה', 'NA''ALE', NULL),
('נעמ"ה', 'NAAMA', NULL),
('נען', 'NA''AN', NULL),
('נצאצרה )שבט(', 'NASASRA', NULL),
('נצר חזני', NULL, NULL),
('נצר סרני', 'NEZER SERENI', NULL),
('נצרת', 'NAZARETH', NULL),
('נצרת עילית', 'NAZERAT ILLIT', NULL),
('נשר', 'NESHER', NULL),
('נתיב הגדוד', 'NETIV HAGEDUD', NULL),
('נתיב הל"ה', 'NETIV HALAMED-HE', NULL),
('נתיב העשרה', 'NETIV HAASARA', NULL),
('נתיב השיירה', 'NETIV HASHAYYARA', NULL),
('נתיבות', 'NETIVOT', NULL),
('נתניה', 'NETANYA', NULL),
('סאג''ור', 'SAJUR', NULL),
('סאסא', 'SASA', NULL),
('סביון', 'SAVYON', NULL),
('סגולה', 'SEGULA', NULL),
('סואעד )חמרייה(', 'SAWA''ID(HAMRIYYE)', NULL),
('סואעד )כמאנה( )שבט(', 'SAWA''ID (KAMANE)', NULL),
('סולם', 'SULAM', NULL),
('סוסיה', 'SUSEYA', NULL),
('סופה', 'SUFA', NULL),
('סח''נין', 'SAKHNIN', NULL),
('סייד )שבט(', 'SAYYID', NULL),
('סלמה', 'SALLAMA', NULL),
('סלעית', 'SAL''IT', NULL),
('סמר', 'SAMAR', NULL),
('סנסנה', NULL, NULL),
('סעד', 'SA''AD', NULL),
('סער', 'SA''AR', NULL),
('ספיר', 'SAPPIR', NULL),
('סתריה', 'SITRIYYA', NULL),
('ע''ג''ר', 'GHAJAR', NULL),
('עבדון', 'AVDON', NULL),
('עברון', 'EVRON', NULL),
('עגור', 'AGUR', NULL),
('עדי', 'ADI', NULL),
('עדנים', 'ADANIM', NULL),
('עוזה', 'UZA', NULL),
('עוזייר', 'UZEIR', NULL),
('עולש', 'OLESH', NULL),
('עומר', 'OMER', NULL),
('עופר', 'OFER', NULL),
('עופרה', 'OFRA', NULL),
('עוצם', 'OZEM', NULL),
('עוקבי )בנו עוקבה(', 'UQBI (BANU UQBA)', NULL),
('עזוז', 'EZUZ', NULL),
('עזר', 'EZER', NULL),
('עזריאל', 'AZRI''EL', NULL),
('עזריה', 'AZARYA', NULL),
('עזריקם', 'AZRIQAM', NULL),
('עטאוונה )שבט(', 'ATAWNE', NULL),
('עטרת', 'ATERET', NULL),
('עידן', 'IDDAN', NULL),
('עיילבון', 'EILABUN', NULL),
('עיינות', 'AYANOT', NULL),
('עילוט', 'ILUT', NULL),
('עין איילה', 'EN AYYALA', NULL),
('עין אל-אסד', 'EIN AL-ASAD', NULL),
('עין גב', 'EN GEV', NULL),
('עין גדי', 'EN GEDI', NULL),
('עין דור', 'EN DOR', NULL),
('עין הבשור', 'EN HABESOR', NULL),
('עין הוד', 'EN HOD', NULL),
('עין החורש', 'EN HAHORESH', NULL),
('עין המפרץ', 'EN HAMIFRAZ', NULL),
('עין הנצי"ב', 'EN HANAZIV', NULL),
('עין העמק', 'EN HAEMEQ', NULL),
('עין השופט', 'EN HASHOFET', NULL),
('עין השלושה', 'EN HASHELOSHA', NULL),
('עין ורד', 'EN WERED', NULL),
('עין זיוון', 'EN ZIWAN', NULL),
('עין חוד', NULL, NULL),
('עין חצבה', 'EN HAZEVA', NULL),
('עין חרוד )איחוד(', 'EN HAROD (IHUD)', NULL),
('עין חרוד )מאוחד(', 'EN HAROD(ME''UHAD)', NULL),
('עין יהב', 'EN YAHAV', NULL),
('עין יעקב', 'EN YA''AQOV', NULL),
('עין כרם-בי"ס חקלאי', 'EN KAREM-B.S.HAQLA''I', NULL),
('עין כרמל', 'EN KARMEL', NULL),
('עין מאהל', 'EIN MAHEL', NULL),
('עין נקובא', 'EIN NAQQUBA', NULL),
('עין עירון', 'EN IRON', NULL),
('עין צורים', 'EN ZURIM', NULL),
('עין קנייא', 'EIN QINIYYE', NULL),
('עין ראפה', 'EIN RAFA', NULL),
('עין שמר', 'EN SHEMER', NULL),
('עין שריד', 'EN SARID', NULL),
('עין תמר', 'EN TAMAR', NULL),
('עינת', 'ENAT', NULL),
('עיר אובות', 'IR OVOT', NULL),
('עכו', 'AKKO', NULL),
('עלומים', 'ALUMIM', NULL),
('עלי', 'ELI', NULL),
('עלי זהב', 'ALE ZAHAV', NULL),
('עלמה', 'ALMA', NULL),
('עלמון', 'ALMON', NULL),
('עמוקה', 'AMUQQA', NULL),
('עמינדב', 'AMMINADAV', NULL),
('עמיעד', 'AMMI''AD', NULL),
('עמיעוז', 'AMMI''OZ', NULL),
('עמיקם', 'AMMIQAM', NULL),
('עמיר', 'AMIR', NULL),
('עמנואל', 'IMMANU''EL', NULL),
('עמקה', 'AMQA', NULL),
('ענב', 'ENAV', NULL),
('עספיא', 'ISIFYA', NULL),
('עפולה', 'AFULA', NULL),
('עץ אפרים', 'EZ EFRAYIM', NULL),
('עצמון שגב', 'ATSMON-SEGEV', NULL),
('עראבה', 'ARRABE', NULL),
('עראמשה', 'ARAMSHA', NULL),
('ערב אל נעים', 'ARRAB AL NAIM', NULL),
('ערד', 'ARAD', NULL),
('ערוגות', 'ARUGOT', NULL),
('ערערה', 'AR''ARA', NULL),
('ערערה-בנגב', 'AR''ARA-BANEGEV', NULL),
('עשרת', 'ASERET', NULL),
('עתלית', 'ATLIT', NULL),
('עתניאל', 'OTNI''EL', NULL),
('פארן', 'PARAN', NULL),
('פדואל', 'PEDU''EL', NULL),
('פדויים', 'PEDUYIM', NULL),
('פדיה', 'PEDAYA', NULL),
('פוריה - כפר עבודה', 'PORIYYA-KEFAR AVODA', NULL),
('פוריה - נווה עובד', 'PORIYYA-NEWE OVED', NULL),
('פוריה עילית', 'PORIYYA ILLIT', NULL),
('פוריידיס', 'FUREIDIS', NULL),
('פורת', 'PORAT', NULL),
('פטיש', 'PATTISH', NULL),
('פלך', 'PELEKH', NULL),
('פלמחים', 'PALMAHIM', NULL),
('פני חבר', 'PENE HEVER', NULL),
('פסגות', 'PESAGOT', NULL),
('פסוטה', 'FASSUTA', NULL),
('פעמי תש"ז', 'PA''AME TASHAZ', NULL),
('פצאל', 'PEZA''EL', NULL),
('פקיעין )בוקייעה(', 'PEQI''IN (BUQEI''A)', NULL),
('פקיעין חדשה', 'PEQI''IN HADASHA', NULL),
('פרדס חנה-כרכור', 'PARDES HANNA-KARKUR', NULL),
('פרדסיה', 'PARDESIYYA', NULL),
('פרוד', 'PAROD', NULL),
('פרזון', 'PERAZON', NULL),
('פרי גן', 'PERI GAN', NULL),
('פתח תקווה', 'PETAH TIQWA', NULL),
('פתחיה', 'PETAHYA', NULL),
('צאלים', 'ZE''ELIM', NULL),
('צביה', 'ZVIYYA', NULL),
('צבעון', 'ZIV''ON', NULL),
('צובה', 'ZOVA', NULL),
('צוחר', 'ZOHAR', NULL),
('צופיה', 'ZOFIYYA', NULL),
('צופים', 'ZUFIN', NULL),
('צופית', 'ZOFIT', NULL),
('צופר', 'ZOFAR', NULL),
('צוקי ים', 'SHOSHANNAT HAAMAQIM(', NULL),
('צוקים', 'MAHANE BILDAD', NULL),
('צור הדסה', 'ZUR HADASSA', NULL),
('צור יצחק', 'ZUR YIZHAQ', NULL),
('צור משה', 'ZUR MOSHE', NULL),
('צור נתן', 'ZUR NATAN', NULL),
('צוריאל', 'ZURI''EL', NULL),
('צורית', 'ZURIT', NULL),
('ציפורי', 'ZIPPORI', NULL),
('צלפון', 'ZELAFON', NULL),
('צנדלה', 'SANDALA', NULL),
('צפריה', 'ZAFRIYYA', NULL),
('צפרירים', 'ZAFRIRIM', NULL),
('צפת', 'ZEFAT', NULL),
('צרופה', 'ZERUFA', NULL),
('צרעה', 'ZOR''A', NULL),
('קבועה )שבט(', 'QABBO''A', NULL),
('קבוצת יבנה', 'QEVUZAT YAVNE', NULL),
('קדומים', 'QEDUMIM', NULL),
('קדימה-צורן', 'QADIMA-ZORAN', NULL),
('קדמה', 'QEDMA', NULL),
('קדמת צבי', 'QIDMAT ZEVI', NULL),
('קדר', 'QEDAR', NULL),
('קדרון', 'QIDRON', NULL),
('קדרים', 'QADDARIM', NULL),
('קודייראת א-צאנע)שבט(', 'QUDEIRAT AS-SANI', NULL),
('קוואעין )שבט(', 'QAWA''IN', NULL),
('קוממיות', 'QOMEMIYYUT', NULL),
('קורנית', 'QORANIT', NULL),
('קטורה', 'QETURA', NULL),
('קיסריה', 'QESARIYYA', NULL),
('קלחים', 'QELAHIM', NULL),
('קליה', 'QALYA', NULL),
('קלנסווה', 'QALANSAWE', NULL),
('קלע', 'QELA', NULL),
('קציר', 'QAZIR', NULL),
('קצר א-סר', NULL, NULL),
('קצרין', 'QAZRIN', NULL),
('קרית אונו', 'QIRYAT ONO', NULL),
('קרית ארבע', 'QIRYAT ARBA', NULL),
('קרית אתא', 'QIRYAT ATTA', NULL),
('קרית ביאליק', 'QIRYAT BIALIK', NULL),
('קרית גת', 'QIRYAT GAT', NULL),
('קרית טבעון', 'QIRYAT TIV''ON', NULL),
('קרית ים', 'QIRYAT YAM', NULL),
('קרית יערים', 'QIRYAT YE''ARIM', NULL),
('קרית יערים)מוסד(', 'QIRYAT YE''ARIM(INSTI', NULL),
('קרית מוצקין', 'QIRYAT MOTZKIN', NULL),
('קרית מלאכי', 'QIRYAT MAL''AKHI', NULL),
('קרית נטפים', 'QIRYAT NETAFIM', NULL),
('קרית ענבים', 'QIRYAT ANAVIM', NULL),
('קרית עקרון', 'QIRYAT EQRON', NULL),
('קרית שלמה', 'QIRYAT SHELOMO', NULL),
('קרית שמונה', 'QIRYAT SHEMONA', NULL),
('קרני שומרון', 'QARNE SHOMERON', NULL),
('קשת', 'QESHET', NULL),
('ראמה', 'RAME', NULL),
('ראס אל-עין', NULL, NULL),
('ראס עלי', 'RAS ALI', NULL),
('ראש העין', 'ROSH HAAYIN', NULL),
('ראש פינה', 'ROSH PINNA', NULL),
('ראש צורים', 'ROSH ZURIM', NULL),
('ראשון לציון', 'RISHON LEZIYYON', NULL),
('רבבה', 'REVAVA', NULL),
('רבדים', 'REVADIM', NULL),
('רביבים', 'REVIVIM', NULL),
('רביד', 'RAVID', NULL),
('רגבה', 'REGBA', NULL),
('רגבים', 'REGAVIM', NULL),
('רהט', 'RAHAT', NULL),
('רווחה', 'REWAHA', NULL),
('רוויה', 'REWAYA', NULL),
('רוח מדבר', 'RUAH MIDBAR', NULL),
('רוחמה', 'RUHAMA', NULL),
('רומאנה', 'RUMMANE', NULL),
('רומת הייב', 'RUMAT HEIB', NULL),
('רועי', 'RO''I', NULL),
('רותם', 'ROTEM', NULL),
('רחוב', 'REHOV', NULL),
('רחובות', 'REHOVOT', NULL),
('רחלים', 'REHELIM', NULL),
('ריחאניה', 'REIHANIYYE', NULL),
('ריחן', 'REHAN', NULL),
('ריינה', 'REINE', NULL),
('רימונים', 'RIMMONIM', NULL),
('רינתיה', 'RINNATYA', NULL),
('רכסים', 'REKHASIM', NULL),
('רם-און', 'RAM-ON', NULL),
('רמות', 'RAMOT', NULL),
('רמות השבים', 'RAMOT HASHAVIM', NULL),
('רמות מאיר', 'RAMOT ME''IR', NULL),
('רמות מנשה', 'RAMOT MENASHE', NULL),
('רמות נפתלי', 'RAMOT NAFTALI', NULL),
('רמלה', 'RAMLA', NULL),
('רמת גן', 'RAMAT GAN', NULL),
('רמת דוד', 'RAMAT DAWID', NULL),
('רמת הכובש', 'RAMAT HAKOVESH', NULL),
('רמת השופט', 'RAMAT HASHOFET', NULL),
('רמת השרון', 'RAMAT HASHARON', NULL),
('רמת יוחנן', 'RAMAT YOHANAN', NULL),
('רמת ישי', 'RAMAT YISHAY', NULL),
('רמת מגשימים', 'RAMAT MAGSHIMIM', NULL),
('רמת צבי', 'RAMAT ZEVI', NULL),
('רמת רזיאל', 'RAMAT RAZI''EL', NULL),
('רמת רחל', 'RAMAT RAHEL', NULL),
('רנן', 'RANNEN', NULL),
('רעים', 'RE''IM', NULL),
('רעננה', 'RA''ANANA', NULL),
('רקפת', 'RAQEFET', NULL),
('רשפון', 'RISHPON', NULL),
('רשפים', 'RESHAFIM', NULL),
('רתמים', 'RETAMIM', NULL),
('שאר ישוב', 'SHE''AR YASHUV', NULL),
('שבי ציון', 'SHAVE ZIYYON', NULL),
('שבי שומרון', 'SHAVE SHOMERON', NULL),
('שבלי - אום אל-גנם', 'SHIBLI', NULL),
('שגב-שלום', 'SEGEV-SHALOM', NULL),
('שדה אילן', 'SEDE ILAN', NULL),
('שדה אליהו', 'SEDE ELIYYAHU', NULL),
('שדה אליעזר', 'SEDE ELI''EZER', NULL),
('שדה בוקר', 'SEDE BOQER', NULL),
('שדה דוד', 'SEDE DAWID', NULL),
('שדה ורבורג', 'SEDE WARBURG', NULL),
('שדה יואב', 'SEDE YO''AV', NULL),
('שדה יעקב', 'SEDE YA''AQOV', NULL),
('שדה יצחק', 'SEDE YIZHAQ', NULL),
('שדה משה', 'SEDE MOSHE', NULL),
('שדה נחום', 'SEDE NAHUM', NULL),
('שדה נחמיה', 'SEDE NEHEMYA', NULL),
('שדה ניצן', 'SEDE NIZZAN', NULL),
('שדה עוזיהו', 'SEDE UZZIYYAHU', NULL),
('שדה צבי', 'SEDE ZEVI', NULL),
('שדות ים', 'SEDOT YAM', NULL),
('שדות מיכה', 'SEDOT MIKHA', NULL),
('שדי אברהם', 'SEDE AVRAHAM', NULL),
('שדי חמד', 'SEDE HEMED', NULL),
('שדי תרומות', 'SEDE TERUMOT', NULL),
('שדמה', 'SHEDEMA', NULL),
('שדמות דבורה', 'SHADMOT DEVORA', NULL),
('שדמות מחולה', 'SHADMOT MEHOLA', NULL),
('שדרות', 'SEDEROT', NULL),
('שואבה', 'SHO''EVA', NULL),
('שובה', 'SHUVA', NULL),
('שובל', 'SHOVAL', NULL),
('שוהם', 'SHOHAM', NULL),
('שומרה', 'SHOMERA', NULL),
('שומריה', 'SHOMERIYYA', NULL),
('שוקדה', 'SHOQEDA', NULL),
('שורש', 'SHORESH', NULL),
('שורשים', 'SHORASHIM', NULL),
('שושנת העמקים', 'SHOSHANNAT HAAMAQIM', NULL),
('שזור', 'SHEZOR', NULL),
('שחר', 'SHAHAR', NULL),
('שחרות', 'SHAHARUT', NULL),
('שיבולים', 'SHIBBOLIM', NULL),
('שיטים', 'NAHAL SHITTIM', NULL),
('שייח'' דנון', 'SHEIKH DANNUN', NULL),
('שילה', 'SHILO', NULL),
('שילת', 'SHILAT', NULL),
('שכניה', 'SHEKHANYA', NULL),
('שלווה', 'SHALWA', NULL),
('שלווה במדבר', 'SHALVA BAMIDBAR', NULL),
('שלוחות', 'SHELUHOT', NULL),
('שלומי', 'SHELOMI', NULL),
('שלומית', NULL, NULL),
('שמיר', 'SHAMIR', NULL),
('שמעה', 'SHIM''A', NULL),
('שמרת', 'SHAMERAT', NULL),
('שמשית', NULL, NULL),
('שני', 'SHANI', NULL),
('שניר', 'SENIR', NULL),
('שעב', 'SHA''AB', NULL),
('שעורים', 'SE''ORIM', NULL),
('שעל', 'SHA''AL', NULL),
('שעלבים', 'SHA''ALVIM', NULL),
('שער אפרים', 'SHA''AR EFRAYIM', NULL),
('שער הגולן', 'SHA''AR HAGOLAN', NULL),
('שער העמקים', 'SHA''AR HAAMAQIM', NULL),
('שער מנשה', 'SHA''AR MENASHE', NULL),
('שערי תקווה', 'SHA''ARE TIQWA', NULL),
('שפיים', 'SHEFAYIM', NULL),
('שפיר', 'SHAFIR', NULL),
('שפר', 'SHEFER', NULL),
('שפרעם', 'SHEFAR''AM', NULL),
('שקד', 'SHAQED', NULL),
('שקף', 'SHEQEF', NULL),
('שרונה', 'SHARONA', NULL),
('שריגים )לי-און(', 'LI-ON', NULL),
('שריד', 'SARID', NULL),
('שרשרת', 'SHARSHERET', NULL),
('שתולה', 'SHETULA', NULL),
('שתולים', 'SHETULIM', NULL),
('תאשור', 'TE''ASHUR', NULL),
('תדהר', 'TIDHAR', NULL),
('תובל', 'TUVAL', NULL),
('תומר', 'TOMER', NULL),
('תושיה', 'TUSHIYYA', NULL),
('תימורים', 'TIMMORIM', NULL),
('תירוש', 'TIROSH', NULL),
('תל אביב - יפו', 'TEL AVIV - YAFO', NULL),
('תל יוסף', 'TEL YOSEF', NULL),
('תל יצחק', 'TEL YIZHAQ', NULL),
('תל מונד', 'TEL MOND', NULL),
('תל עדשים', 'TEL ADASHIM', NULL),
('תל קציר', 'TEL QAZIR', NULL),
('תל שבע', 'TEL SHEVA', NULL),
('תל תאומים', 'TEL TE''OMIM', NULL),
('תלם', 'TELEM', NULL),
('תלמי אליהו', 'TALME ELIYYAHU', NULL),
('תלמי אלעזר', 'TALME EL''AZAR', NULL),
('תלמי ביל"ו', 'TALME BILU', NULL),
('תלמי יוסף', 'TALME YOSEF', NULL),
('תלמי יחיאל', 'TALME YEHI''EL', NULL),
('תלמי יפה', 'TALME YAFE', NULL),
('תלמים', 'TELAMIM', NULL),
('תמרת', 'TIMRAT', NULL),
('תנובות', 'TENUVOT', NULL),
('תעוז', 'TA''OZ', NULL),
('תפרח', 'TIFRAH', NULL),
('תקומה', 'TEQUMA', NULL),
('תקוע', 'TEQOA', NULL),
('תראבין א-צאנע )שבט(', 'TARABIN AS-SANI', NULL),
('תראבין א-צאנע)ישוב(', NULL, NULL),
('תרום', 'TARUM', NULL) ON CONFLICT (name) DO NOTHING;
